/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgriYield,
  IAgriYieldInterface,
} from "../../../contracts/Marketplace.sol/IAgriYield";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "farmId",
        type: "uint256",
      },
    ],
    name: "getFarm",
    outputs: [
      {
        internalType: "address",
        name: "farmer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "fundingGoal",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "raised",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "proceeds",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "shareSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sharePrice",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "metaCID",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAgriYield__factory {
  static readonly abi = _abi;
  static createInterface(): IAgriYieldInterface {
    return new Interface(_abi) as IAgriYieldInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAgriYield {
    return new Contract(address, _abi, runner) as unknown as IAgriYield;
  }
}
