/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAgriYieldInterface extends Interface {
  getFunction(nameOrSignature: "getFarm"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFarm",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getFarm", data: BytesLike): Result;
}

export interface IAgriYield extends BaseContract {
  connect(runner?: ContractRunner | null): IAgriYield;
  waitForDeployment(): Promise<this>;

  interface: IAgriYieldInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFarm: TypedContractMethod<
    [farmId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        farmer: string;
        fundingGoal: bigint;
        raised: bigint;
        proceeds: bigint;
        shareSupply: bigint;
        sharePrice: bigint;
        status: bigint;
        metaCID: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFarm"
  ): TypedContractMethod<
    [farmId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        farmer: string;
        fundingGoal: bigint;
        raised: bigint;
        proceeds: bigint;
        shareSupply: bigint;
        sharePrice: bigint;
        status: bigint;
        metaCID: string;
      }
    ],
    "view"
  >;

  filters: {};
}
