/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IHederaTokenServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createFungibleToken"
      | "grantTokenKyc"
      | "mintToken"
      | "revokeTokenKyc"
      | "transferToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createFungibleToken",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      boolean,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "grantTokenKyc",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintToken",
    values: [AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTokenKyc",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToken",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createFungibleToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantTokenKyc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeTokenKyc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToken",
    data: BytesLike
  ): Result;
}

export interface IHederaTokenService extends BaseContract {
  connect(runner?: ContractRunner | null): IHederaTokenService;
  waitForDeployment(): Promise<this>;

  interface: IHederaTokenServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createFungibleToken: TypedContractMethod<
    [
      name: string,
      symbol: string,
      memo: string,
      maxSupply: BigNumberish,
      decimals: BigNumberish,
      freezeDefaultStatus: boolean,
      metadata: BytesLike[]
    ],
    [[bigint, string]],
    "payable"
  >;

  grantTokenKyc: TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "nonpayable"
  >;

  mintToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, metadata: BytesLike[]],
    [bigint],
    "nonpayable"
  >;

  revokeTokenKyc: TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "nonpayable"
  >;

  transferToken: TypedContractMethod<
    [
      token: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createFungibleToken"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      memo: string,
      maxSupply: BigNumberish,
      decimals: BigNumberish,
      freezeDefaultStatus: boolean,
      metadata: BytesLike[]
    ],
    [[bigint, string]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "grantTokenKyc"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, metadata: BytesLike[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeTokenKyc"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
